### ISSUE TITLE
请问文章如何插入链接。

### ISSUE THREAD

**Issue by MaoVlog** [bigfa/hugo-theme-farallon#1]
我是以Markdown 格式插入的。[Markdown测试]  (https://baidu.com/) 
 结果总链接后显示网址。
![QQ20231106-084315](https://github.com/bigfa/hugo-theme-farallon/assets/98894817/161e1614-bf7a-4fa4-bb9e-7e4e5d7b8412)

**Comment by bigfa** [comment]
修复啦，重新拉下代码就行了。
