### ISSUE TITLE
自写样式部署后失效

### ISSUE THREAD

**Issue by suuseer** [bigfa/hugo-theme-farallon#2]
按照hugo文档，覆写了样式及字体，部署后失效，请教大佬

**Comment by bigfa** [comment]
你这基本没提供什么信息，无法判断啊

**Comment by suuseer** [comment]
https://eclectic-cat-6188bb.netlify.app/
我就是在大佬基础上想把字体改下，比如文章下面的头像，这些东西，改后部署就没有样式了

**Comment by bigfa** [comment]
部署的域名没有改，还是我的域名，改成你自己的域名。
