### ISSUE TITLE
关于代码块 

### ISSUE THREAD

**Issue by jkjoy** [bigfa/hugo-theme-farallon#3]
代码块 在light模式下 无法看清代码  背景太黑了

**Comment by bigfa** [comment]
https://bigfa.github.io/hugo-theme-farallon/story/hugo-theme-farallon/

没啥问题啊，你是不是自己加了代码高亮啥的。

**Comment by jkjoy** [comment]
木有啊 我直接从你仓库 fork 的

**Comment by bigfa** [comment]
看了下的地址，你那用了代码高亮啊，我看是内链样式。直接用`pre`标签就好了，代码高亮的话要自己写兼容代码，不过这种内链直接写死也没法兼容。。

**Comment by jkjoy** [comment]
好的谢谢
